### ISSUE TITLE
Unable to load D3_data_viz.sql file in drupal database

### ISSUE THREAD

**Issue by rniti** [deviantpixel/d3_data_viz#1]
I was trying to run your code and for that I tried to import d3datavis_2016-07-20.sql file and it throws error regarding cache so I deleted all cache values but still it throwing error like #1367 - Illegal double '147846E639' value found during parsing. Could you please help me.

Thanks in advance,

**Comment by rniti** [comment]
and this error too "#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'The entity id this data is attached to',
  `revision_id` int(10) unsigned NOT NU' at line 3 "

**Comment by deviantpixel** [comment]
Should be OK now. I just rebased everything on Drupal 8.3. Export was created via Drush fyi.
